# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BadWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=35, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomShortUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom', models.CharField(db_index=True, max_length=35, null=True, unique=True)),
                ('hash_id', models.IntegerField(db_index=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='URLShortened',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortened', models.CharField(db_index=True, max_length=35, unique=True)),
                ('original', models.URLField(db_index=True, max_length=250, unique=True)),
                ('count', models.IntegerField(default=0)),
                ('hash_id', models.IntegerField(db_index=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='customshorturl',
            name='url_associated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shorten.URLShortened'),
        ),
    ]
